// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

const defaultEnvPath = path.resolve(
  process.cwd(),
  "..",
  "..",
  "cachecash-config",
  ".env"
);

dotenv.config({ path: process.env.ENV_FILE_PATH ?? defaultEnvPath });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
